from pathlib import Path
import re
p=Path('src/main.jsx')
s=p.read_text()
start=s.find('function AdminPeople(')
end=s.find('function AdminGiras(', start)
if start<0 or end<0:
    raise SystemExit('AdminPeople/AdminGiras boundary not found')
fn=r'''function AdminPeople({p}){
 const [rows,setRows]=useState([]),[groups,setGroups]=useState([]),[edit,setEdit]=useState(null),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{const[{data:ps,error:e1},{data:gs,error:e2}]=await Promise.all([supabase.from('profiles').select('id,name,email,role,group_id,is_iniciado,is_active,leadership_seal,orixa_symbol,groups(id,name)').order('name'),supabase.from('groups').select('id,name,is_operational_default').order('name')]);if(e1||e2){setMsg((e1||e2).message);return}setRows(ps||[]);setGroups(gs||[])}
 useEffect(()=>{load()},[])
 const save=async()=>{if(!edit)return;setBusy(true);setMsg('');const{error}=await supabase.rpc('admin_set_profile',{p_profile_id:edit.id,p_role:edit.role,p_group_id:edit.group_id,p_leadership_seal:edit.leadership_seal||null,p_is_iniciado:!!edit.is_iniciado,p_is_active:!!edit.is_active});if(error)setMsg(error.message);else{setMsg('Cadastro atualizado.');setEdit(null);await load()}setBusy(false)}
 const filtered=rows.filter(r=>(`${r.name||''} ${r.email||''} ${r.role||''} ${r.groups?.name||''}`.toLowerCase()).includes(q.toLowerCase()))
 return <div className="card"><div className="row between"><div><span className="eyebrow">PESSOAS</span><h3 style={{margin:'6px 0'}}>Quem faz a casa</h3><p className="muted small">Cadastros, grupos, liderança e acesso.</p></div><button className="btn" onClick={load}><RefreshCw size={15}/> Atualizar</button></div>{msg&&<div className="toast">{msg}</div>}<div className="field"><label>Buscar</label><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, e-mail, grupo ou papel"/></div><div className="list">{filtered.map(r=><div className="list-item" key={r.id}><div className="row between"><div className="row"><OrixaIcon name={r.orixa_symbol} size={32}/><div><b>{r.name}</b><div className="muted small">{r.email} · {r.groups?.name||'Sem grupo'} · {r.role==='admin'?'Administrador':r.role==='editor'?'Editor':'Membro'}</div></div></div><button className="btn" onClick={()=>setEdit({...r,group_id:r.group_id||groups.find(g=>g.name==='Organização')?.id||'',leadership_seal:r.leadership_seal||'',is_iniciado:!!r.is_iniciado,is_active:!!r.is_active})}>Editar</button></div><div className="row" style={{marginTop:8}}>{r.is_iniciado&&<span className="pill">INICIADO</span>}{r.leadership_seal&&<span className="pill">LIDERANÇA · {r.leadership_seal}</span>}<span className="pill">{r.is_active?'ATIVO':'INATIVO'}</span></div></div>)}{filtered.length===0&&<div className="empty">Nenhuma pessoa encontrada.</div>}</div>{edit&&<Modal title={'Editar · '+edit.name} close={()=>setEdit(null)}><Field label="Perfil"><select className="select" value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}><option value="member">Membro</option><option value="editor">Editor</option><option value="admin">Administrador</option></select></Field><Field label="Grupo de atuação"><select className="select" value={edit.group_id||''} onChange={e=>setEdit({...edit,group_id:e.target.value})}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Selo de liderança"><select className="select" value={edit.leadership_seal||''} onChange={e=>setEdit({...edit,leadership_seal:e.target.value})}><option value="">Sem selo</option><option>Comunicação</option><option>Organização Geral</option><option>Decoração</option><option>Cozinha</option><option>Manutenção</option></select></Field><div className="row"><button className="btn" onClick={()=>setEdit({...edit,is_iniciado:!edit.is_iniciado})}>{edit.is_iniciado?'Iniciado ✓':'Marcar como Iniciado'}</button><button className="btn" onClick={()=>setEdit({...edit,is_active:!edit.is_active})}>{edit.is_active?'Ativo':'Inativo'}</button></div><button className="btn primary" style={{marginTop:12}} disabled={busy} onClick={save}>{busy?'Salvando…':'Salvar alterações'}</button></Modal>}</div>}
'''
p.write_text(s[:start]+fn+'\n'+s[end:])
