import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Home, CalendarDays, Leaf, UserRound, WalletCards, BookOpen, Settings, UsersRound, ClipboardList, Megaphone, ArrowRight, Clock3, Check, X, Plus, ChevronRight, CircleDollarSign, LogOut, Mail, ShieldCheck, RefreshCw, Trash2, UserCog } from 'lucide-react'
import { supabase } from './lib/supabase'
import './styles.css'

const periods = ['Sexta-feira','Sábado · 14h30–15h30','Sábado · pós-gira','Domingo']
const periodKeys = {'Sexta-feira':'friday','Sábado · 14h30–15h30':'saturday_1430','Sábado · pós-gira':'saturday_post_gira','Domingo':'sunday'}
const periodLabels = {friday:'Sexta-feira',saturday_1430:'Sábado · 14h30–15h30',saturday_post_gira:'Sábado · pós-gira',sunday:'Domingo'}
const nav = [{id:'home',label:'Início',icon:Home},{id:'giras',label:'Giras',icon:CalendarDays},{id:'community',label:'Comunidade',icon:Leaf},{id:'me',label:'Eu',icon:UserRound}]

function App(){
 const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [loading,setLoading]=useState(true); const [screen,setScreen]=useState('home')
 const loadProfile=async(user)=>{if(!user){setProfile(null);return} const {data}=await supabase.from('profiles').select('*, groups(name,is_operational_default)').eq('id',user.id).maybeSingle(); setProfile(data)}
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);await loadProfile(data.session?.user);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange(async(_e,s)=>{setSession(s); if(s?.user) await loadProfile(s.user); else setProfile(null)}); return()=>subscription.unsubscribe()},[])
 if(loading)return <Splash/>
 if(!session)return <AuthScreen/>
 const signOut=async()=>{await supabase.auth.signOut();setScreen('home')}; const go=id=>setScreen(id)
 return <div className="app-shell"><header className="topbar"><div className="brand-mark">PBC</div><div><span className="eyebrow">Terreiro Pai Benedito do Congo</span><strong>Axé, comunidade.</strong></div><div className="top-user">{profile?.orixa_symbol||'🌿'}</div></header><main className="content">{screen==='home'&&<HomeScreen profile={profile} go={go}/>} {screen==='giras'&&<GirasScreen profile={profile}/>} {screen==='community'&&<CommunityScreen profile={profile}/>} {screen==='me'&&<MeScreen profile={profile} go={go} signOut={signOut}/>} {screen==='admin'&&profile?.role==='admin'&&<AdminScreen profile={profile}/>}</main><BirthdayBar/><nav className="bottom-nav">{nav.map(({id,label,icon:Icon})=><button key={id} className={screen===id?'active':''} onClick={()=>go(id)}><Icon size={20}/><span>{label}</span></button>)}</nav></div>
}

function Splash(){return <div className="splash"><div className="brand-mark">PBC</div><h1>Terreiro Pai Benedito do Congo</h1><p>Carregando a casa…</p></div>}
function AuthScreen(){const [mode,setMode]=useState('login');const [code,setCode]=useState('');const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 const checkCode=async()=>{setMessage('');const {data,error}=await supabase.rpc('validate_invitation',{p_code:code.trim()});if(error||!data?.length){setRole(null);setMessage('Código inválido, usado, revogado ou expirado.');return}setRole(data[0]);if(data[0].intended_name&&!name)setName(data[0].intended_name);if(data[0].intended_email&&!email)setEmail(data[0].intended_email)}
 const submit=async e=>{e.preventDefault();setMessage('');setBusy(true);try{if(mode==='register'){if(!role){await checkCode();setBusy(false);return} const {error}=await supabase.auth.signUp({email,password,options:{data:{name,invite_code:code.trim()}}});if(error)throw error;setMessage('Conta criada. Se a confirmação por e-mail estiver ativa, confira sua caixa de entrada para entrar na casa.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}}catch(err){setMessage(err.message||'Não foi possível concluir.')}finally{setBusy(false)}}
 return <div className="auth-wrap"><div className="auth-card"><div className="auth-brand"><div className="brand-mark">PBC</div><span className="eyebrow">Terreiro Pai Benedito do Congo</span></div><h1>{mode==='login'?'Bem-vindo de volta.':'Entre para a casa.'}</h1><p className="muted">{mode==='login'?'Acesse sua área da comunidade.':'Use o código recebido para criar seu acesso.'}</p>{message&&<div className="form-message">{message}</div>}<form onSubmit={submit}>{mode==='register'&&<><label>Nome<input value={name} onChange={e=>setName(e.target.value)} required /></label><label>Código de convite<div className="code-row"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="PBC-XXXXXXXXXXXX" required /><button type="button" onClick={checkCode}>Validar</button></div></label>{role&&<div className="invite-valid"><ShieldCheck size={16}/> Convite válido para <strong>{role.role==='admin'?'Administrador':role.role==='editor'?'Editor':'Membro'}</strong></div></>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Senha<input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required /></label><button className="primary-button" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar':'Criar minha conta'}</button></form><button className="switch-auth" onClick={()=>{setMode(mode==='login'?'register':'login');setMessage('');setRole(null)}}>{mode==='login'?'Tenho um código de convite':'Já tenho uma conta'}</button></div></div>}

function HomeScreen({profile,go}){const [gira,setGira]=useState(null);const [response,setResponse]=useState(null);const [loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const {data}=await supabase.from('giras').select('*').gte('starts_at',new Date().toISOString()).order('starts_at').limit(1).maybeSingle();setGira(data);if(data){const r=await supabase.from('gira_responses').select('*').eq('gira_id',data.id).eq('profile_id',profile.id).maybeSingle();setResponse(r.data)}setLoading(false)})()},[profile.id]);const save=async(status)=>{if(!gira)return;const {data,error}=await supabase.from('gira_responses').upsert({gira_id:gira.id,profile_id:profile.id,status},{onConflict:'gira_id,profile_id'}).select().single();if(!error)setResponse(data)}
 return <><section className="hero"><span className="eyebrow">Boa tarde, {profile.name?.split(' ')[0]}</span><h1>Que a casa esteja<br/><em>em harmonia.</em></h1><p className="muted">Tudo que você precisa para acompanhar a vida da casa, em um só lugar.</p></section>{loading?<div className="loading-card">Carregando a próxima gira…</div>:gira?<><section className="gira-card featured"><div className="gira-art"><span>🌿</span></div><div className="gira-info"><span className="pill">PRÓXIMA GIRA</span><h2>{gira.name}</h2><p className="date"><CalendarDays size={15}/>{formatDate(gira.starts_at)}</p>{gira.what_to_bring&&<p className="muted small">Levar: {gira.what_to_bring}</p>}<button className="text-button" onClick={()=>go('giras')}>Ver detalhes <ArrowRight size={16}/></button></div></section><section className="presence-card"><strong>Você vai participar?</strong><span>Confirme sua presença para a próxima gira.</span><div className="choice-row"><button className={response?.status==='going'?'selected':''} onClick={()=>save('going')}><Check size={15}/> Vou participar</button><button className={response?.status==='not_going'?'selected no':''} onClick={()=>save('not_going')}><X size={15}/> Não vou</button></div>{response&&<small className="saved">Resposta registrada.</small>}</section></>:<div className="memory-card"><strong>Nenhuma gira cadastrada ainda.</strong><p className="muted">Quando a próxima gira for publicada, ela aparecerá aqui.</p></div>}<Notice/><div className="shortcut-grid"><Shortcut icon={<CalendarDays/>} title="Giras" onClick={()=>go('giras')}/><Shortcut icon={<Leaf/>} title="Comunidade" onClick={()=>go('community')}/><Shortcut icon={<WalletCards/>} title="Financeiro" onClick={()=>go('me')}/><Shortcut icon={<BookOpen/>} title="Informações da casa" onClick={()=>go('me')}/></div></>}
function Notice(){const [notice,setNotice]=useState(null);useEffect(()=>{supabase.from('notices').select('*').eq('published',true).order('starts_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>setNotice(data))},[]);if(!notice)return null;return <section className="notice"><div className="notice-icon"><Megaphone size={18}/></div><div><span className="eyebrow">{notice.title||'AVISO DA CASA'}</span><p>{notice.body}</p></div></section>}
function Shortcut({icon,title,onClick}){return <button className="shortcut" onClick={onClick}>{icon}<span>{title}</span></button>}

function GirasScreen({profile}){const [giras,setGiras]=useState([]);const [selected,setSelected]=useState(null);const [response,setResponse]=useState(null);const [availability,setAvailability]=useState([]);const load=()=>supabase.from('giras').select('*').order('starts_at').then(({data})=>setGiras(data||[]));useEffect(()=>{load()},[]);const open=async(g)=>{setSelected(g);const {data}=await supabase.from('gira_responses').select('*, gira_availability(period_key)').eq('gira_id',g.id).eq('profile_id',profile.id).maybeSingle();setResponse(data);setAvailability(data?.gira_availability?.map(x=>x.period_key)||[])};const save=async(status)=>{const {data,error}=await supabase.from('gira_responses').upsert({gira_id:selected.id,profile_id:profile.id,status},{onConflict:'gira_id,profile_id'}).select().single();if(!error){setResponse(data);if(status==='not_going'){await supabase.from('gira_availability').delete().eq('gira_response_id',data.id);setAvailability([])}}};const togglePeriod=async(p)=>{if(!response||response.status!=='going')return;const key=periodKeys[p];if(availability.includes(key)){await supabase.from('gira_availability').delete().eq('gira_response_id',response.id).eq('period_key',key);setAvailability(availability.filter(x=>x!==key))}else{const {error}=await supabase.from('gira_availability').insert({gira_response_id:response.id,period_key:key});if(!error)setAvailability([...availability,key])}}
 return <section><PageTitle eyebrow="CALENDÁRIO DA CASA" title="Giras" subtitle="Acompanhe as próximas e anteriores."/>{selected?<><button className="back-link" onClick={()=>setSelected(null)}>← Todas as giras</button><article className="gira-detail gira-card"><div className="gira-art detail-art"><span>🌾</span></div><div className="gira-info"><span className="pill">GIRA</span><h2>{selected.name}</h2><p className="date"><CalendarDays size={15}/>{formatDate(selected.starts_at)}</p>{selected.what_to_bring&&<p className="muted small">Levar: {selected.what_to_bring}</p>}{selected.notes&&<p className="muted small">{selected.notes}</p>}{selected.contribution_amount!=null&&<p className="contribution">Contribuição <strong>R$ {Number(selected.contribution_amount).toFixed(2).replace('.',',')}</strong></p>}<div className="presence-block"><strong>Você vai participar?</strong><div className="choice-row"><button className={response?.status==='going'?'selected':''} onClick={()=>save('going')}>✓ Vou participar</button><button className={response?.status==='not_going'?'selected no':''} onClick={()=>save('not_going')}>Não vou</button></div>{response?.status==='going'&&<><strong className="help-title">Quero ajudar</strong><div className="periods">{periods.map(p=><button key={p} className={availability.includes(periodKeys[p])?'selected':''} onClick={()=>togglePeriod(p)}>{p}</button>)}</div></>}</div></div></article></>:<GiraList giras={giras} onOpen={open}/>}</section>}
function GiraList({giras,onOpen}){const groups=giras.reduce((a,g)=>{const k=new Date(g.starts_at).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});(a[k]??=[]).push(g);return a},{});return <>{Object.entries(groups).map(([month,items])=><div key={month}><h3 className="section-title">{month.charAt(0).toUpperCase()+month.slice(1)}</h3>{items.map(g=><button className="gira-card compact" key={g.id} onClick={()=>onOpen(g)}><div className="gira-art small-art">🌱</div><div className="gira-info"><span className="pill">GIRA</span><h2>{g.name}</h2><p className="date"><Clock3 size={15}/>{formatDate(g.starts_at)}</p>{g.contribution_amount!=null&&<p className="muted small">Contribuição: R$ {Number(g.contribution_amount).toFixed(2).replace('.',',')}</p>}</div><ChevronRight className="chevron" size={19}/></button>)}</div>)}{!giras.length&&<div className="memory-card">Nenhuma gira cadastrada.</div>}</>}

function CommunityScreen({profile}){const [posts,setPosts]=useState([]);const [open,setOpen]=useState(false);const [body,setBody]=useState('');const [kind,setKind]=useState('reflexao');const load=async()=>{const {data}=await supabase.from('community_posts').select('id,author_id,body,kind,created_at,gira_id,profiles!community_posts_author_id_fkey(name,orixa_symbol),giras(name)').order('created_at',{ascending:false});setPosts(data||[])};useEffect(()=>{load()},[]);const publish=async()=>{if(!body.trim())return;const {error}=await supabase.from('community_posts').insert({author_id:profile.id,body:body.trim(),kind});if(!error){setBody('');setOpen(false);load()}};const remove=async(id)=>{await supabase.from('community_posts').delete().eq('id',id);load()};return <section><PageTitle eyebrow="NOSSA COMUNIDADE" title="Mural" subtitle="Ensinamentos, reflexões e o que ficou de cada gira."/><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={17}/> Compartilhar algo com a casa</button><div className="post-list">{posts.map(p=><Post key={p.id} post={p} own={p.author_id===profile.id} onDelete={()=>remove(p.id)}/>)}{!posts.length&&<div className="memory-card">Ainda não há publicações. Seja a primeira pessoa a deixar um registro.</div>}</div>{open&&<Modal title="Compartilhar com a casa" onClose={()=>setOpen(false)}><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value)}><option value="ensinamento">Ensinamento</option><option value="reflexao">Reflexão</option><option value="senti">O que senti</option></select></label><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="O que você quer deixar registrado?" autoFocus/><button className="primary-button" onClick={publish}>Publicar</button></Modal>}</section>}
function Post({post,own,onDelete}){return <article className="post"><div className="avatar">{post.profiles?.orixa_symbol||'🌿'}</div><div className="post-content"><div><strong>{post.profiles?.name||'Membro da casa'}</strong>{post.profiles?.orixa_symbol&&<span className="post-meta"> · {post.profiles.orixa_symbol}</span>}</div><p>{post.body}</p><small>{post.kind==='ensinamento'?'Ensinamento':post.kind==='senti'?'O que senti':'Reflexão'} · {formatRelative(post.created_at)}{post.giras?.name?` · ${post.giras.name}`:''}</small>{own&&<button className="delete-link" onClick={onDelete}>Excluir</button>}</div></article>}

function MeScreen({profile,go,signOut}){const [charges,setCharges]=useState([]);const [dues,setDues]=useState([]);useEffect(()=>{supabase.from('monthly_dues').select('*').eq('profile_id',profile.id).order('reference_month',{ascending:false}).limit(12).then(({data})=>setDues(data||[]));supabase.from('extra_charges').select('*').eq('profile_id',profile.id).order('due_date',{ascending:false}).then(({data})=>setCharges(data||[]))},[profile.id]);return <section><PageTitle eyebrow="SEU ESPAÇO" title="Eu" subtitle="Seu perfil, seus registros e informações importantes."/><div className="profile-card"><div className="avatar large">{profile.orixa_symbol||'🌿'}</div><div><h2>{profile.name}</h2><p className="muted">{profile.groups?.name||'Organização'} {profile.leadership_seal&&` · ${profile.leadership_seal}`}</p></div></div><div className="menu-card"><MenuRow icon={<WalletCards/>} title="Meu financeiro" detail="Mensalidades e outras cobranças" onClick={()=>document.getElementById('financeiro')?.scrollIntoView({behavior:'smooth'})}/><MenuRow icon={<BookOpen/>} title="Informações da casa" detail="Regras e orientações"/><MenuRow icon={<UserRound/>} title="Meu perfil" detail="Dados e símbolo de Orixá"/><MenuRow icon={<Settings/>} title="Configurações" detail="Preferências da conta"/></div>{(dues.length||charges.length)>0&&<section id="financeiro" className="finance-card"><span className="eyebrow">MEU FINANCEIRO</span><h2>Registros financeiros</h2>{dues.map(d=><FinanceRow key={d.id} label={monthLabel(d.reference_month)} status={d.status}/>) }{charges.map(c=><FinanceRow key={c.id} label={c.description} detail={c.due_date?`Vencimento ${formatDateOnly(c.due_date)}`:''} amount={c.amount} status={c.status}/>)}</section>}<button className="admin-link" onClick={()=>profile.role==='admin'&&go('admin')} disabled={profile.role!=='admin'}><UsersRound size={17}/> Administração {profile.role==='admin'?'':'(restrita aos administradores)'}<ChevronRight size={17}/></button><button className="logout" onClick={signOut}><LogOut size={16}/> Sair</button></section>}
function FinanceRow({label,detail,amount,status}){return <div className="finance-row"><div><strong>{label}</strong>{detail&&<small>{detail}</small>}</div>{amount!=null&&<b>R$ {Number(amount).toFixed(2).replace('.',',')}</b>}<span className={`status ${status==='paid'?'paid':'unpaid'}`}>{status==='paid'?'Pago':'Não pago'}</span></div>}
function MenuRow({icon,title,detail,onClick}){return <button className="menu-row" onClick={onClick}>{icon}<div><strong>{title}</strong><small>{detail}</small></div><ChevronRight size={17}/></button>}

function AdminScreen({profile}){const [tab,setTab]=useState('people');const [giras,setGiras]=useState([]);const [members,setMembers]=useState([]);const [groups,setGroups]=useState([]);const [cats,setCats]=useState([]);const [selectedGira,setSelectedGira]=useState('');const [tasks,setTasks]=useState([]);const [assignments,setAssignments]=useState([]);const [invitations,setInvitations]=useState([]);const [contents,setContents]=useState([]);const [notice,setNotice]=useState(null);const [message,setMessage]=useState('');const [modal,setModal]=useState(null);const [busy,setBusy]=useState(false)
 const refresh=async()=>{const [g,m,gr,c,i,h,n]=await Promise.all([supabase.from('giras').select('*').order('starts_at'),supabase.from('profiles').select('id,name,email,role,group_id,is_active,is_iniciado,leadership_seal,groups(name)').order('name'),supabase.from('groups').select('*').order('name'),supabase.from('task_categories').select('*').order('name'),supabase.from('invitations').select('*').order('created_at',{ascending:false}),supabase.from('house_contents').select('*').order('sort_order').order('title'),supabase.from('notices').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle()]);setGiras(g.data||[]);setMembers(m.data||[]);setGroups(gr.data||[]);setCats(c.data||[]);setInvitations(i.data||[]);setContents(h.data||[]);setNotice(n.data||null);if(!selectedGira&&g.data?.[0])setSelectedGira(g.data[0].id)}
 const loadTasks=async(id)=>{if(!id){setTasks([]);setAssignments([]);return}const [t,a]=await Promise.all([supabase.from('tasks').select('*, task_categories(name)').eq('gira_id',id).order('period_key').order('sort_order'),supabase.from('task_assignments').select('*, profiles(name,group_id,leadership_seal), tasks!inner(gira_id,name,period_key)').eq('tasks.gira_id',id)]);setTasks(t.data||[]);setAssignments(a.data||[])}
 useEffect(()=>{refresh()},[]);useEffect(()=>{loadTasks(selectedGira)},[selectedGira])
 const saveGira=async(form)=>{setBusy(true);setMessage('');const payload={name:form.name,starts_at:new Date(form.starts_at).toISOString(),what_to_bring:form.what_to_bring||null,contribution_amount:Number(form.contribution_amount||0),contribution_due_date:form.contribution_due_date||null,notes:form.notes||null,created_by:profile.id,updated_by:profile.id};const q=form.id?supabase.from('giras').update({...payload,created_by:undefined}).eq('id',form.id):supabase.from('giras').insert(payload);const {error}=await q;if(error)setMessage(error.message);else{setModal(null);await refresh()}setBusy(false)}
 const deleteGira=async(id)=>{if(!confirm('Excluir esta gira e suas tarefas/participações?'))return;const {error}=await supabase.from('giras').delete().eq('id',id);setMessage(error?error.message:'Gira excluída.');await refresh()}
 const seed=async()=>{if(!selectedGira)return;setBusy(true);const {data,error}=await supabase.rpc('seed_gira_tasks',{p_gira_id:selectedGira});setMessage(error?error.message:`${data||0} tarefas preparadas para esta gira.`);await loadTasks(selectedGira);setBusy(false)}
 const draw=async()=>{if(!selectedGira)return;if(!confirm('Sortear as tarefas desta gira? O sorteio considera disponibilidade, evita mais de uma tarefa por período e não inclui lideranças. Tarefas de Iniciados ficam fora do sorteio até definirmos a regra.'))return;setBusy(true);const {data,error}=await supabase.rpc('draw_gira_tasks',{p_gira_id:selectedGira});setMessage(error?error.message:`Sorteio concluído: ${data||0} vagas distribuídas.`);await loadTasks(selectedGira);setBusy(false)}
 const createInvite=async(form)=>{setBusy(true);const code=`PBC-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`;const {error}=await supabase.from('invitations').insert({code,role:form.role,intended_name:form.intended_name||null,intended_email:form.intended_email||null,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null,created_by:profile.id});if(error)setMessage(error.message);else{setMessage(`Convite criado: ${code}`);setModal(null);await refresh()}setBusy(false)}
 const revoke=async(id)=>{await supabase.from('invitations').update({status:'revoked'}).eq('id',id);refresh()}
 const updateMember=async(m,patch)=>{const {error}=await supabase.from('profiles').update(patch).eq('id',m.id);if(error)setMessage(error.message);else await refresh()}
 const generateDues=async()=>{setBusy(true);const month=new Date();const reference_month=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-01`;const rows=members.filter(m=>m.is_active).map(m=>({profile_id:m.id,reference_month,status:'unpaid',updated_by:profile.id}));const {error}=await supabase.from('monthly_dues').upsert(rows,{onConflict:'profile_id,reference_month'});setMessage(error?error.message:`Mensalidades de ${monthLabel(reference_month)} preparadas para ${rows.length} pessoas.`);setBusy(false)}
 const toggleDue=async(d)=>{const next=d.status==='paid'?'unpaid':'paid';const {error}=await supabase.from('monthly_dues').update({status:next,updated_by:profile.id}).eq('id',d.id);if(error)setMessage(error.message);else setModal(null)}
 const saveContent=async(f)=>{setBusy(true);const q=f.id?supabase.from('house_contents').update({title:f.title,body:f.body,sort_order:Number(f.sort_order||0),updated_by:profile.id}).eq('id',f.id):supabase.from('house_contents').insert({title:f.title,body:f.body,sort_order:Number(f.sort_order||0),created_by:profile.id,updated_by:profile.id});const {error}=await q;setMessage(error?error.message:'Conteúdo salvo.');if(!error){setModal(null);refresh()}setBusy(false)}
 if(profile.role!=='admin')return null
 return <section><PageTitle eyebrow="ADMINISTRAÇÃO" title="Gestão da casa" subtitle="Tudo que precisa ser organizado, em um só lugar."/><div className="admin-tabs">{[['people','Pessoas',UsersRound],['giras','Giras',CalendarDays],['tasks','Tarefas',ClipboardList],['finance','Financeiro',CircleDollarSign],['content','Conteúdos',BookOpen],['invites','Convites',Mail]].map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</div>{message&&<div className="form-message admin-message">{message}<button onClick={()=>setMessage('')}><X size={15}/></button></div>}
 {tab==='people'&&<AdminPeople members={members} groups={groups} onUpdate={updateMember}/>} {tab==='giras'&&<AdminGiras giras={giras} onNew={()=>setModal({type:'gira'})} onEdit={g=>setModal({type:'gira',data:{...g,starts_at:toLocalInput(g.starts_at)}})} onDelete={deleteGira}/>} {tab==='tasks'&&<AdminTasks giras={giras} selected={selectedGira} setSelected={setSelectedGira} tasks={tasks} assignments={assignments} onSeed={seed} onDraw={draw} busy={busy}/>} {tab==='finance'&&<AdminFinance members={members} onGenerate={generateDues} busy={busy}/>} {tab==='content'&&<AdminContent contents={contents} notice={notice} onNew={()=>setModal({type:'content'})} onEdit={c=>setModal({type:'content',data:c})} onRefresh={refresh}/>} {tab==='invites'&&<AdminInvites invitations={invitations} onNew={()=>setModal({type:'invite'})} onRevoke={revoke}/>} {modal?.type==='gira'&&<GiraForm initial={modal.data} onClose={()=>setModal(null)} onSave={saveGira} busy={busy}/>} {modal?.type==='invite'&&<InviteForm onClose={()=>setModal(null)} onSave={createInvite} busy={busy}/>} {modal?.type==='content'&&<ContentForm initial={modal.data} onClose={()=>setModal(null)} onSave={saveContent} busy={busy}/>}</section>}

function AdminPeople({members,groups,onUpdate}){return <section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">PESSOAS</span><h2>{members.length} perfis</h2></div></div><div className="admin-list">{members.map(m=><article className="admin-row" key={m.id}><div className="avatar">{m.role==='admin'?'🛡️':m.role==='editor'?'✦':'🌿'}</div><div className="admin-row-main"><strong>{m.name}</strong><small>{m.email||'Sem e-mail visível'} · {m.groups?.name||'Organização'}{m.leadership_seal?` · Selo: ${m.leadership_seal}`:''}</small><div className="inline-controls"><select value={m.role} onChange={e=>onUpdate(m,{role:e.target.value})}><option value="member">Membro</option><option value="editor">Editor</option><option value="admin">Administrador</option></select><select value={m.group_id||''} onChange={e=>onUpdate(m,{group_id:e.target.value||null})}><option value="">Organização</option>{groups.filter(g=>g.name!=='Organização').map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input value={m.leadership_seal||''} placeholder="Selo de liderança" onChange={e=>onUpdate(m,{leadership_seal:e.target.value||null})}/><label className="mini-check"><input type="checkbox" checked={!!m.is_iniciado} onChange={e=>onUpdate(m,{is_iniciado:e.target.checked})}/> Iniciado</label><button className={m.is_active?'soft-button':'soft-button danger'} onClick={()=>onUpdate(m,{is_active:!m.is_active})}>{m.is_active?'Ativo':'Inativo'}</button></div></div></article>)}</div></section>}
function AdminGiras({giras,onNew,onEdit,onDelete}){return <section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">CALENDÁRIO</span><h2>Giras</h2></div><button className="primary-button small-button" onClick={onNew}><Plus size={16}/> Nova gira</button></div>{giras.map(g=><article className="admin-row" key={g.id}><div className="avatar">🌿</div><div className="admin-row-main"><strong>{g.name}</strong><small>{formatDate(g.starts_at)} · {g.contribution_amount>0?`R$ ${Number(g.contribution_amount).toFixed(2).replace('.',',')}`:'Sem contribuição'}</small><div className="row-actions"><button className="soft-button" onClick={()=>onEdit(g)}>Editar</button><button className="soft-button danger" onClick={()=>onDelete(g.id)}><Trash2 size={15}/> Excluir</button></div></div></article>)}{!giras.length&&<div className="memory-card">Nenhuma gira cadastrada.</div>}</section>}
function AdminTasks({giras,selected,setSelected,tasks,assignments,onSeed,onDraw,busy}){const assignedCount=assignments.length;return <section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">ORGANIZAÇÃO</span><h2>Tarefas e sorteio</h2></div><div className="row-actions"><button className="soft-button" onClick={onSeed} disabled={!selected||busy}><RefreshCw size={15}/> Preparar tarefas</button><button className="primary-button small-button" onClick={onDraw} disabled={!selected||busy}>🎲 Sortear</button></div></div><label>Gira<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione uma gira</option>{giras.map(g=><option key={g.id} value={g.id}>{g.name} · {formatDate(g.starts_at)}</option>)}</select></label>{selected&&<><div className="task-summary"><span>{tasks.reduce((s,t)=>s+t.slots,0)} vagas comuns</span><span>{assignedCount} atribuições no sorteio</span><span>Iniciados: regra própria</span></div><div className="task-list">{periods.map(p=>{const key=periodKeys[p];const rows=tasks.filter(t=>t.period_key===key);return <div className="period-card" key={key}><div className="period-head"><strong>{p}</strong><small>{rows.reduce((s,t)=>s+t.slots,0)} vagas</small></div>{rows.length?rows.map(t=><div className="task-line" key={t.id}><span>{t.name}<small>{t.task_categories?.name||'Sem categoria'} · {t.slots} vagas</small></span><b>{assignments.filter(a=>a.task_id===t.id).length}/{t.slots}</b></div>):<small className="muted">Nenhuma tarefa preparada.</small>}</div>})}</div><div className="people-without-task"><strong>Após o sorteio</strong><span>As lideranças ficam fora do sorteio. Atribuições manuais podem ser feitas pelos administradores.</span></div></>}</section>}
function AdminFinance({members,onGenerate,busy}){const [dues,setDues]=useState([]);const [charges,setCharges]=useState([]);const [person,setPerson]=useState('');const [form,setForm]=useState({description:'',amount:'',due_date:''});const load=async()=>{const [d,c]=await Promise.all([supabase.from('monthly_dues').select('*,profiles(name)').order('reference_month',{ascending:false}).limit(500),supabase.from('extra_charges').select('*,profiles(name)').order('due_date',{ascending:false}).limit(500)]);setDues(d.data||[]);setCharges(c.data||[])};useEffect(()=>{load()},[]);const toggle=async d=>{await supabase.from('monthly_dues').update({status:d.status==='paid'?'unpaid':'paid'}).eq('id',d.id);load()};const add=async()=>{if(!person||!form.description||form.amount==='')return;const {error}=await supabase.from('extra_charges').insert({profile_id:person,description:form.description,amount:Number(form.amount),due_date:form.due_date||null});if(!error){setForm({description:'',amount:'',due_date:''});setPerson('');load()}};return <section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">FINANCEIRO</span><h2>Mensalidades e cobranças</h2></div><button className="soft-button" onClick={()=>{onGenerate();setTimeout(load,500)}} disabled={busy}>Gerar mensalidades do mês</button></div><div className="finance-admin-form"><select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Pessoa para cobrança extra</option>{members.filter(m=>m.is_active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input placeholder="Descrição" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Valor" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/><button className="primary-button small-button" onClick={add}><Plus size={15}/> Cobrar</button></div><h3 className="section-title">Mensalidades</h3>{dues.map(d=><div className="finance-row admin-finance-row" key={d.id}><div><strong>{d.profiles?.name}</strong><small>{monthLabel(d.reference_month)}</small></div><button className={`status ${d.status==='paid'?'paid':'unpaid'}`} onClick={()=>toggle(d)}>{d.status==='paid'?'Pago':'Não pago'}</button></div>)}<h3 className="section-title">Outras cobranças</h3>{charges.map(c=><div className="finance-row admin-finance-row" key={c.id}><div><strong>{c.profiles?.name}</strong><small>{c.description}{c.due_date?` · ${formatDateOnly(c.due_date)}`:''}</small></div><b>R$ {Number(c.amount).toFixed(2).replace('.',',')}</b><span className={`status ${c.status==='paid'?'paid':'unpaid'}`}>{c.status==='paid'?'Pago':'Não pago'}</span></div>)}</section>}
function AdminContent({contents,notice,onNew,onEdit,onRefresh}){const remove=async id=>{await supabase.from('house_contents').delete().eq('id',id);onRefresh()};return <section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">CONTEÚDOS DA CASA</span><h2>Informações permanentes</h2></div><button className="primary-button small-button" onClick={onNew}><Plus size={15}/> Novo conteúdo</button></div>{contents.map(c=><article className="admin-row" key={c.id}><div className="admin-row-main"><strong>{c.title}</strong><small>{c.body.slice(0,120)}{c.body.length>120?'…':''}</small><div className="row-actions"><button className="soft-button" onClick={()=>onEdit(c)}>Editar</button><button className="soft-button danger" onClick={()=>remove(c.id)}>Excluir</button></div></div></article>)}<div className="notice-admin"><strong>Avisos da Home</strong><small>{notice?notice.title:'Nenhum aviso publicado'}</small></div></section>}
function AdminInvites({invitations,onNew,onRevoke}){return <section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">ACESSOS</span><h2>Convites</h2></div><button className="primary-button small-button" onClick={onNew}><Plus size={15}/> Criar convite</button></div>{invitations.map(i=><article className="admin-row" key={i.id}><div className="avatar">{i.role==='admin'?'🛡️':i.role==='editor'?'✦':'🌿'}</div><div className="admin-row-main"><strong>{i.code}</strong><small>{i.role==='admin'?'Administrador':i.role==='editor'?'Editor':'Membro'}{i.intended_name?` · ${i.intended_name}`:''}{i.intended_email?` · ${i.intended_email}`:''}</small><div className="row-actions"><span className={`status ${i.status==='active'?'paid':'unpaid'}`}>{i.status}</span>{i.status==='active'&&<button className="soft-button danger" onClick={()=>onRevoke(i.id)}>Revogar</button>}</div></div></article>)}</section>}

function GiraForm({initial,onClose,onSave,busy}){const [f,setF]=useState(initial||{name:'',starts_at:'',what_to_bring:'',contribution_amount:'0',contribution_due_date:'',notes:''});const set=(k,v)=>setF({...f,[k]:v});return <Modal title={initial?'Editar gira':'Nova gira'} onClose={onClose}><label>Nome<input value={f.name} onChange={e=>set('name',e.target.value)} required /></label><label>Data e hora<input type="datetime-local" value={f.starts_at} onChange={e=>set('starts_at',e.target.value)} required /></label><label>O que levar<input value={f.what_to_bring||''} onChange={e=>set('what_to_bring',e.target.value)}/></label><label>Contribuição<input type="number" min="0" step="0.01" value={f.contribution_amount??0} onChange={e=>set('contribution_amount',e.target.value)}/></label><label>Vencimento da contribuição<input type="date" value={f.contribution_due_date||''} onChange={e=>set('contribution_due_date',e.target.value)}/></label><label>Observações<textarea value={f.notes||''} onChange={e=>set('notes',e.target.value)}/></label><button className="primary-button" onClick={()=>onSave(f)} disabled={busy}>{busy?'Salvando…':'Salvar gira'}</button></Modal>}
function InviteForm({onClose,onSave,busy}){const [f,setF]=useState({role:'member',intended_name:'',intended_email:'',expires_at:''});const set=(k,v)=>setF({...f,[k]:v});return <Modal title="Novo convite" onClose={onClose}><label>Tipo<select value={f.role} onChange={e=>set('role',e.target.value)}><option value="member">Membro</option><option value="editor">Editor</option><option value="admin">Administrador</option></select></label><label>Nome (opcional)<input value={f.intended_name} onChange={e=>set('intended_name',e.target.value)}/></label><label>E-mail (opcional)<input type="email" value={f.intended_email} onChange={e=>set('intended_email',e.target.value)}/></label><label>Validade (opcional)<input type="datetime-local" value={f.expires_at} onChange={e=>set('expires_at',e.target.value)}/></label><button className="primary-button" onClick={()=>onSave(f)} disabled={busy}>{busy?'Criando…':'Gerar convite'}</button></Modal>}
function ContentForm({initial,onClose,onSave,busy}){const [f,setF]=useState(initial||{title:'',body:'',sort_order:0});const set=(k,v)=>setF({...f,[k]:v});return <Modal title={initial?'Editar conteúdo':'Novo conteúdo'} onClose={onClose}><label>Título<input value={f.title} onChange={e=>set('title',e.target.value)} required /></label><label>Conteúdo<textarea rows="8" value={f.body} onChange={e=>set('body',e.target.value)} required /></label><label>Ordem<input type="number" value={f.sort_order||0} onChange={e=>set('sort_order',e.target.value)}/></label><button className="primary-button" onClick={()=>onSave(f)} disabled={busy}>{busy?'Salvando…':'Salvar conteúdo'}</button></Modal>}

function BirthdayBar(){const [people,setPeople]=useState([]);useEffect(()=>{supabase.from('profiles').select('name,date_of_birth').eq('is_active',true).not('date_of_birth','is',null).then(({data})=>setPeople(data||[]))},[]);const month=new Date().getMonth()+1;const birthday=people.filter(p=>new Date(p.date_of_birth+'T12:00:00').getMonth()+1===month).sort((a,b)=>new Date(a.date_of_birth)-new Date(b.date_of_birth));return <footer className="birthday-bar"><span>🎂</span><div><strong>Aniversariantes de {new Intl.DateTimeFormat('pt-BR',{month:'long'}).format(new Date())}</strong><small>{birthday.length?birthday.map(p=>`${p.name.split(' ')[0]} ${p.date_of_birth.slice(8,10)}/${p.date_of_birth.slice(5,7)}`).join(' · '):'Nenhum aniversariante cadastrado neste mês.'}</small></div></footer>}
function PageTitle({eyebrow,title,subtitle}){return <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="muted">{subtitle}</p></div>}
function Modal({title,onClose,children}){return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
function formatDate(v){return new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function formatDateOnly(v){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function formatRelative(v){const d=new Date(v),days=Math.floor((Date.now()-d.getTime())/86400000);if(days<1)return'Hoje';if(days===1)return'Ontem';return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}
function monthLabel(v){return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function toLocalInput(v){const d=new Date(v);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}

createRoot(document.getElementById('root')).render(<App/>);